### ISSUE TITLE
Different naming for debug and release file libs

### ISSUE THREAD

**Issue by DJuego** [Lichtso/netLink#12]
I suggest different "names" for lib and release lib files. For example;

For example;

Debug:
netLink-d.dll
netLink-d.lib
Release:
netLink.dll
netLink.lib

In this way the Lib files could share directory. Also it avoids "accidents".

Perhaps with: 
set_target_properties( netLink PROPERTIES DEBUG_POSTFIX -d )

**Comment by Lichtso** [comment]
Done, usage example:

    mkdir build && cd build
    cmake .. -DCMAKE_BUILD_TYPE=debug
