### ISSUE TITLE
getType()

### ISSUE THREAD

**Issue by DJuego** [Lichtso/netLink#13]
I am struggling with serialization and related content. :-(.  In the next example:

```C++
int main()
{

//STAGE 1
    std::vector<std::unique_ptr<MsgPack::Element>> arrayWith3Elements;
    arrayWith3Elements.push_back(MsgPack::Factory(static_cast<uint64_t>(1)));
    arrayWith3Elements.push_back(MsgPack::Factory(static_cast<int64_t>(177)));
    arrayWith3Elements.push_back(MsgPack::Factory(static_cast<float>(-64.0f)));
    arrayWith3Elements.push_back(MsgPack::Factory(static_cast<double>(-64.0f)));

    std::unique_ptr<MsgPack::Element> p = MsgPack__Factory(Array(std::move(arrayWith3Elements)));

//STAGE 2
    auto array= dynamic_cast<MsgPack::Array*>(p.get());
    if (array)
    {
        auto contenedor = array->getContainer();
        for (auto const &elemento : (*contenedor))
        {

            MsgPack::Type type = elemento->getType();
            switch (type)
            {
            case MsgPack::UINT_64:
            {
                std::cout << "UINT64" << std::endl;
                break;
            }
            case MsgPack::INT_64:
            {
                std::cout << "INT64" << std::endl;
                break;
            }
            case MsgPack::FLOAT_32:
            {
                std::cout << "FLOAT32" << std::endl;
                break;
            }
            case MsgPack::FLOAT_64:
            {
                std::cout << "FLOAT64" << std::endl;
                break;
            }
            default:
                std::cout << "UNKNOWN" << std::endl;
                break;

            }
        }
    }
    std::cin.get();
    return 0;
}
```

The expected output was:
```
UINT64
INT64
FLOAT32
FLOAT64

```
The output was:

```
UNKNOWN
UNKNOWN
FLOAT32
FLOAT64
```

Why "UNKNOWN"?

:-/

**Comment by Lichtso** [comment]
Well, it is all according to the spec: https://github.com/msgpack/msgpack/blob/master/spec.md#overview
If you print out the types correctly (I gotta admit, just fixed the type normalization, but that does not matter), you get:

    FIXUINT
    INT_16
    FLOAT32
    FLOAT64

That is because, MsgPack wants the type chosen, to be as small as possible to hold a value.
So anyway, why do you need to know the actual type of the value?
You can call Number.getValue<traget type>(); on any given type to cast to another.

**Comment by DJuego** [comment]
Thank you for your swift and instructive answer, again. :-). Yes. 

Context:
I try to implement a "broadcast" system for a TCP server with netLink. My current approach is, basically;


``` C++
for (auto const &socketitr : servidorsocket->clients)
                        {
							std::unique_ptr<MsgPack::Element> B = nullptr;
							CloneMsgPackToMsgPack(A, B);							
                            netLink::MsgPackSocket& msgPackSocket = *static_cast<netLink::MsgPackSocket*>(socketitr.get());
							msgPackSocket << std::move(B);
							
                        }

```
I would want a 'general' function to clone any simple MsgPack array:

``` C++
int CloneMsgPackToMsgPack(const std::unique_ptr<MsgPack::Element> &A std::unique_ptr<MsgPack::Element> &B);`
```
I return to original code:

``` C++
int main()
{
    std::vector<std::unique_ptr<MsgPack::Element>> arrayWith3Elements;
    arrayWith3Elements.push_back(MsgPack::Factory(static_cast<uint64_t>(2334)));
    
    std::unique_ptr<MsgPack::Element> p = MsgPack__Factory(Array(std::move(arrayWith3Elements)));

    auto array= dynamic_cast<MsgPack::Array*>(p.get());
    if (array)
    {
        auto contenedor = array->getContainer();
		for (auto const &elemento : (*contenedor))
		{
			auto elementocontenido = dynamic_cast<MsgPack::Number*>(elemento.get());
			//auto valor1 = elementocontenido->getValue(); //I need to know the type but I don´t know the type. :-/
			auto valor2 = elementocontenido->getValue<uint64_t>(); //it Works.
			std::cout << "The value is " << valor2 << std::endl; 
		}
            
    }
    std::cin.get();
    return 0;
}
```

**Comment by Lichtso** [comment]
Well, I will try to add some helper methods for your needs by tomorrow.
Maybe a copy constructor for MsgPack Elements or a more specific type qualifier.

Do you want to broadcast all data homogenously or do you want to distinguish different sources and destinations? Because if you just want to retransmit the same data, you would not have to parse MsgPack at all but could redirect the raw bytes as stream instead.

**Comment by DJuego** [comment]
Thank you very much Lichtso. You are sensitive to your users'needs. 

It works wonderfully for my use-case. I hope that the philosophy of your design does not look affected negatively with this addition. I think it is a intuitive/useful addition and other use cases will easily appear.

 Yes. I wanted to broadcast the same data. Honestly, there were approaches on the table, but they seemed me too ugly and complicated/convoluted for implementing a simple... well... a simple broadcast.

You can close this issue. : +1: :

DJuego

**Comment by Lichtso** [comment]
Well, I am glad this approach works for you.

But it has some disadvantages:
1. Deserializing and reserializing the elements again needs additional processor time
2. Deep copy of the elements needs additional memory
3. Because elements need to be received completely before they are redirected, it adds latency to the connections

I will try to add a broadcast method to optimize it by redirecting the raw streams directly.

**Comment by DJuego** [comment]
Yeah.  I agree with your analysis. A specific and efficient broadcast method would be better.  I believe that it is a sufficiently common need for synchronization.

 Mainly I worry about the problem of latency. High-performance is highly desirable. Although I would understand that you decide to give priority to KISS principle and a clean/elegant/friendly design.

Anyways  in the my pet-project context it is much too soon to think about profiling and benchmarks :-)

**Comment by Lichtso** [comment]
I added a Socket::redirect(destinations) method, which can be used like this:

    socketManager.onReceive = [&](netLink::SocketManager* manager, std::shared_ptr<netLink::Socket> source) {
        std::vector<std::shared_ptr<netLink::Socket>> destinations;
        for(const auto& iter : socketManager.sockets)
            if(iter->getType() == netLink::Socket::Type::TCP_SERVERS_CLIENT)
                destinations.push_back(iter);
        
        source->redirect(destinations);
    };
    
Beware, it is much faster and more efficent
but less safe as it can't undo transmission errors and
you can't analyze the data before redirecting it,
so it is a raw byte-wise (not message-wise) redirection.

It is up too you to decide between Socket::redirect or MsgPack::Element::copy.

**Comment by DJuego** [comment]
An unexpected gift! Being able to choose is a pleasure. I am going to have to rebuild netLink :-D 
I like very much the custom-made destination list. Probably I will stick at the original plan because I  foresee that I will need more control:  I keep doubts on the stability of a MindStorms EV3 (https://en.wikipedia.org/wiki/Lego_Mindstorms_EV3)  wifi network.

However,  I promise test Socket::redirect very soon. :-)
