### ISSUE TITLE
sputc compare issue

### ISSUE THREAD

**Issue by yassy0413** [Lichtso/netLink#15]
In ndk r10e, when the value of BOOL_FALSE, sputc> 0 is fail to data inconsistencies will happening. If it is changed as follows: I think the best.

streamBuffer-> sputc (type)> 0
↓
streamBuffer-> sputc (type)! = std :: basic_streambuf <char> :: traits_type :: eof ()

@see http://www.dcs.uni-pannon.hu/smidla/web/cplusplus/reference/iostream/streambuf/sputc/index.html

thank you

**Comment by Lichtso** [comment]
Done: 13f3d12

**Comment by yassy0413** [comment]
Thank you very mush!
