### ISSUE TITLE
Building with Visual Studio 2015

### ISSUE THREAD

**Issue by DJuego** [Lichtso/netLink#16]
Hello Lichtso!  I have come back! :-)

I simply wanted to report to you that **netlink** seems not to get compiled with Microsoft Visual Studio 14.0.

I have attached a full log for:

```
cmake -G 'NMake Makefiles' -D CMAKE_BUILD_TYPE=Debug -D CMAKE_INSTALL_PREFIX=$DIRECTORIO_LOCAL -D DOXYGEN_EXECUTABLE=$ARCHIVO_DOXYGEN -D DOXYGEN_DOT_EXECUTABLE=$ARCHIVO_DOT  ../..	
nmake	
```

and

  ```
cmake -G 'NMake Makefiles' -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=$DIRECTORIO_LOCAL -D DOXYGEN_EXECUTABLE=$ARCHIVO_DOXYGEN -D DOXYGEN_DOT_EXECUTABLE=$ARCHIVO_DOT  ../..		
nmake
```

However, it builds like a charm in MinGW 5.3.0 

P.S: I have the same problem with: cmake -G 'Visual Studio 14 2015'

![output log netlink](https://cloud.githubusercontent.com/assets/1956212/16498925/f2ddcbd8-3ef5-11e6-996a-581902502af1.png)

**Comment by Lichtso** [comment]
I don't have any windows machines at the moment but I might access one by tomorrow.

Which version of cmake and platform (Win 7, 8, 10) are you using?

**Comment by DJuego** [comment]
- :-) 
- Windows 10.x64
- CMake version 3.5.2

**Comment by Lichtso** [comment]
Upgraded from 8 to 10 or is it a fresh installation?
Do you experience similar problems with other C++11 code?

**Comment by DJuego** [comment]
- Fresh installation
- No. No problem. Boost 1.61, OpenCV 3.1.0, SFML 2.3.2 and so on...  (in the same environment (machine, Windows 10 x64, Microsoft Visual Studio 14.0., cmake version...)
- I have had never this problem.

P.S: I am using the netLink github version.

**Comment by Lichtso** [comment]
The github version?

Also lets take a look at your build command:
`cmake
    -G 'NMake Makefiles'
    -D CMAKE_BUILD_TYPE=Release
    -D CMAKE_INSTALL_PREFIX=$DIRECTORIO_LOCAL
    -D DOXYGEN_EXECUTABLE=$ARCHIVO_DOXYGEN
    -D DOXYGEN_DOT_EXECUTABLE=$ARCHIVO_DOT 
    ../..`

DOXYGEN_EXECUTABLE and DOXYGEN_DOT_EXECUTABLE are not needed as the docs are pre built. CMAKE_BUILD_TYPE=Debug / Release does not really matter, the outcome should be the same,
so testing only "Release" is enough.

I just pushed a commit: 2e992cd
Could you pull it and execute these two commands:

cmake -G 'NMake Makefiles' -D CMAKE_BUILD_TYPE=Release ../..
cmake -G 'Visual Studio 14 2015' -D CMAKE_BUILD_TYPE=Release ../..

Search for these values (and post them):

CXX_FLAGS =
CXX_DEFINES =
_WIN32_WINNT=
WINVER=

in a file like CMakeFiles/static.dir/flags.make
the path might be a bit different on windows and nmake,
but a recursive text search should find it anyway.


Thanks

**Comment by DJuego** [comment]
Yep!

 CMakeFiles/static.dir/flags.make (same path :-))
```
# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.5

# compile CXX with C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
CXX_FLAGS =  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1  

CXX_DEFINES = -DWINVER=0x0100000100050806 -D_WIN32_WINNT=0x0100000100050806

CXX_INCLUDES = -IP:\Plataformas\x32-x64\TRABAJO_MSVC2015_x64\netLink\PUBLIC -IP:\Plataformas\x32-x64\TRABAJO_MSVC2015_x64\netLink\include 

```

P.S:

> The github version?

Yes. The master version. The most recent version with the very last commit. Sorry for my English. :-/

![output log netlink v2](https://cloud.githubusercontent.com/assets/1956212/16517089/8c71aee0-3f73-11e6-9b82-1a1f8c874677.png)

**Comment by Lichtso** [comment]
This might fix it: cc051d1

**Comment by DJuego** [comment]
yes, yes, yes, YES!!

Thanks and congrats, Lichtso! The most valuable asset of **netLink** are you yourself. :-)

I attach you the output log in case you want to face some warnings.
![output log netlink v3](https://cloud.githubusercontent.com/assets/1956212/16520965/96395dca-3f8b-11e6-8e5f-1389ccc0ee8d.png)

**Comment by Lichtso** [comment]
Thanks, I will take a look at it.

The problem explained:
Like the Millennium bug when 1999+1 became 19100 instead of 2000,
0x0A00 became 0x01000 because of the missing dec to hex conversion.
Windows 10 is simply the first version with 2 digits.
