### ISSUE TITLE
socketmanager and ONE TcpServer socket

### ISSUE THREAD

**Issue by DJuego** [Lichtso/netLink#21]
Hi again!

 This code produce an exception in Windows (Visual Studio 2015) in 			socketManager.listen(5.0);

 is it normal?? :-O

DJuego

```cpp


int main(int argc, char** argv) {
	//#ifdef WINVER
	netLink::init();
	//#endif

	netLink::SocketManager socketManager;
	std::shared_ptr<netLink::Socket> socket = socketManager.newSocket();
	try
	{
		socket->initAsTcpServer("0.0.0.0", 3015);
	}
	catch (netLink::Exception exc)
	{
		std::cout << "Address is already in use" << std::endl;
		return 1;
	}
	socket->setBlockingMode(false);

	socketManager.onReceiveRaw = [](netLink::SocketManager *manager, std::shared_ptr< netLink::Socket > socket)
		{

			std::cout << "Receiving..." << std::endl;			
		};


		while (true)
			socketManager.listen(5.0);


	return 0;
}

```

**Comment by Lichtso** [comment]
Which Windows version are you using?
Can you use a debugger to find where it is thrown?

You have to build and run it with the debug flag on to get useful info:
cmake -DCMAKE_BUILD_TYPE=Debug .

The error message and stack trace gained from the debugger would help.

**Comment by DJuego** [comment]
I am working in Windows 10 x64.

Okas, @Lichtso . I get a net::Excepcion ERROR_SELECT(2).

When i trace the exception (step by step),  i find:

```cpp
if(select(maxHandle+1, NULL, &writefds, NULL, timeoutPtr) == -1)
       throw Exception(Exception::ERROR_SELECT);
```
 I have not idea however I wonder if the problem will not be because there are no valid sockets (not TCP_SERVERS_CLIENTS) for select.  (is it correct?)

_selection_ is not empty() because selection contains the TCP_SERVER (without TCP_SERVERS_CLIENTS) socket... 

DJuego

**Comment by Lichtso** [comment]
Thx, could you print out the value of errno inside the if but before the throw?

```
if(select(maxHandle+1, NULL, &writefds, NULL, timeoutPtr) == -1) {
    printf("maxHandle %d, Errno: %d, %s\n", maxHandle, errno, strerror(errno));
    throw Exception(Exception::ERROR_SELECT);
}
```

This might require:
```
#include <errno.h>
```

**Comment by DJuego** [comment]
Ok, @Lichtso 

I get:

_maxHandle 276, Errno: 0, No error
Exception in Listen_

run again:

_maxHandle 224, Errno: 0, No error
Exception in Listen_

run again:
_maxHandle 304, Errno: 0, No error
Exception in Listen_

My code is:

```cpp
#include <iostream>
#include <netLink/netLink.h>

int main(int argc, char** argv) {
	//#ifdef WINVER
	netLink::init();
	//#endif

	netLink::SocketManager socketManager;
	std::shared_ptr<netLink::Socket> socket = socketManager.newSocket();
	try
	{
		socket->initAsTcpServer("0.0.0.0", 3015);
		//socket->initAsTcpServer("*", 3016);
	}
	catch (netLink::Exception exc)
	{
		std::cout << "Address is already in use" << std::endl;
		return 1;
	}
	socket->setBlockingMode(false);

	socketManager.onReceiveRaw = [](netLink::SocketManager *manager, std::shared_ptr< netLink::Socket > socket)
		{

			std::cout << "Receiving..." << std::endl;			
		};


	while (socket->getStatus() != netLink::Socket::Status::NOT_CONNECTED)
	{
		try
		{
			socketManager.listen(5.0);
		}
		catch (netLink::Exception exc)
		{
			std::cout << "Exception in Listen" << std::endl;
			return 1;
		}
	}
	return 0;
}
```

**Comment by Lichtso** [comment]
That is a strange behavior of the operating system, usually the errno should be set if select returns -1. What confuses me even more are the high handle numbers.

Could you print out the socket->handle in foreach_e(sockets, iterator)?
And also replace the == -1 with == SOCKET_ERROR after both select() calls?

**Comment by DJuego** [comment]
Ok! I print out the value of [WSAGetLastError](https://msdn.microsoft.com/es-es/library/windows/desktop/ms741580(v=vs.85).aspx)

```cpp
    if(select(maxHandle+1, NULL, &writefds, NULL, timeoutPtr) == -1)
	{
		printf("WSAGetLastError: %d", WSAGetLastError());
		printf("maxHandle %d, Errno: %d, %s\n", maxHandle, errno, strerror(errno));
        throw Exception(Exception::ERROR_SELECT);
	}
```
 I get: 

WSAGetLastError: 10022

About the [select documentation](https://msdn.microsoft.com/es-es/library/windows/desktop/ms740141(v=vs.85).aspx):

_WSAEINVAL(10022): **The time-out value is not valid, or all three descriptor parameters were null.**

Generic description
WSAEINVAL(10022): Invalid argument.
Some invalid argument was supplied (for example, specifying an invalid level to the setsockopt function). In some instances, it also refers to the current state of the socket—for instance, calling accept on a socket that is not listening.

Now, i am going to follow your instructions...

**Comment by DJuego** [comment]
With the changes you suggested I get:

WSAGetLastError: 10022
maxHandle 224, Errno: 0, No error

As expected, there are not client handles because there are not clients...

This output is generated by:

```cpp
    if(select(maxHandle+1, NULL, &writefds, NULL, timeoutPtr) == SOCKET_ERROR)
	{
		printf("WSAGetLastError: %d \n", WSAGetLastError());
		printf("maxHandle %d, Errno: %d, %s\n", maxHandle, errno, strerror(errno));
        throw Exception(Exception::ERROR_SELECT);
	}

```

**Comment by Lichtso** [comment]
Ah, I totally forgot about WSAGetLastError on windows, my bad.

The absence of clients is expected.
However, there should be at least the sever socket->handle.
Try to measure it around line 67 after:
```
foreach_e(sockets, iterator) {
        Socket* socket = (*iterator).get();
```

Another idea is to replace timeoutPtr by NULL in both calls to select().

**Comment by DJuego** [comment]
Yes, yes. Sorry. My bad. I get the server handle now. For instance;

socket handle: 272
WSAGetLastError: 10022
maxHandle 272, Errno: 0, No error

Now i retry with timeoutPtr to NULL (both calls to select):

socket handle: 260
WSAGetLastError: 10022
maxHandle 260, Errno: 0, No error

**Comment by DJuego** [comment]
I am an ignorant :-((( but Could the problem be in **writefds**?
In
```cpp
if(select(maxHandle+1, NULL, &writefds, NULL, NULL) == SOCKET_ERROR)
```
As the socket is a TCP_SERVER there are no:
```cpp
FD_SET(socket->handle, &writefds);
```
And of course, as there are not clients, there are no:

```cpp
FD_SET(client->handle, &writefds);
```
is it normal?

**Comment by Lichtso** [comment]
Yes, if timeoutPtr isn't the problem and maxHandle is ignored (according to the documentation) then writefds has to be the cause. I suspect that the new windows version interprets an empty fd_set as NULL ptr, even though this should be allowed.

Anyway, try to add the extra condition "writefds.fd_count > 0" before the first select() call:
`if(writefds.fd_count > 0 && select(maxHandle+1, NULL, &writefds, NULL, timeoutPtr) == -1)`

**Comment by DJuego** [comment]
**Yes**, @Lichtso . With the extra condition, the listen seems work. In fact, the official example tcp.cpp works now. Of course, more exhaustive test is necessary. :-)

DJuego

P.S: I hope there are no side effects... (for instance in other OS)  :-/

**Comment by Lichtso** [comment]
Thx for your remote debugging efforts. 👍
I'll include this via macro so the extra condition is only evaluated in windows.
