### ISSUE TITLE
initAsTcpServer("*", port);

### ISSUE THREAD

**Issue by DJuego** [Lichtso/netLink#22]
Sorry, @Lichtso .  Again me.

I am using Windows 10 x64 with Visual Studio 2015.

Briefly;

_initAsTcpServer("0.0.0.0", port);_  works 
_but initAsTcpServer("*", port);_ does **not** work (IPv6 is selected automatically)
In fact,  initAsTcpServer("::0", 3823); does **not** work 

Sample Code:

```cpp
#include <iostream>
#include <netLink/netLink.h>
int main(int argc, char** argv) 
{
//#ifdef WINVER
	netLink::init();
//#endif
	netLink::SocketManager socketManager;
	std::shared_ptr<netLink::Socket> socket = socketManager.newSocket();
	try 
	{		
		//socket->initAsTcpServer("0.0.0.0", 3823);
		socket->initAsTcpServer("*", 3823);
	}
	catch (netLink::Exception exc)
	{
		std::cout << "Exception: "<< exc.code << std::endl; //I get ERROR_SET_SOCK_OPT(3)
	}
}
```

The exception occurs in  Socket::initSocket (Socket.cpp)

```cpp
if(ipVersion == IPv6) {
            flag = 0;
            if(setsockopt(handle, IPPROTO_IPV6, IPV6_V6ONLY, &flag, sizeof(flag)) == -1) {
                disconnect();
                throw Exception(Exception::ERROR_SET_SOCK_OPT);
            }
```

```

**Comment by Lichtso** [comment]
Here again, could you try WSAGetLastError() inside the if before disconnect()?

And try to replace flag with: 
```
unsigned int flag2 = 0;
if(setsockopt(handle, IPPROTO_IPV6, IPV6_V6ONLY, &flag2, sizeof(flag2)) == -1) {
```

**Comment by DJuego** [comment]
The change you propose is not possible:

`Socket.cpp(228): error C2664: 'int setsockopt(SOCKET,int,int,const char *,int)': cannot convert argument 4 from 'unsigned int *' to 'const char *'`

I suppose you want to say:

```cpp
char flag2 = 0;
if(setsockopt(handle, IPPROTO_IPV6, IPV6_V6ONLY, &flag2, sizeof(flag2)) == -1) {
```

I get:

```
if(ipVersion == IPv6) {
            char flag2 = 0;
            if(setsockopt(handle, IPPROTO_IPV6, IPV6_V6ONLY, &flag2, sizeof(flag2)) == -1) {
				printf("WSAGetLastError: %d \n", WSAGetLastError());
                disconnect();
                throw Exception(Exception::ERROR_SET_SOCK_OPT);
            }
        }
```

The output is:

WSAGetLastError: 10014

In the documentation for [setsockopt function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740476(v=vs.85).aspx) i see:
WSAEFAULT (10014)
_The buffer pointed to by the optval parameter is not in a valid part of the process address space or the optlen parameter is too small._

**Comment by Lichtso** [comment]
I meant `unsigned int`, but you are right, you have to cast it to the right pointer type:
`static_cast<void*>(&flag2)`
Else the optlen parameter is too small because sizeof(char) -> 1 and I suspect it to want 4 bytes.

**Comment by DJuego** [comment]
Unfortunately with your change I get:

`error C2664: 'int setsockopt(SOCKET,int,int,const char *,int)': cannot convert argument 4 from 'void *' to 'const char *'`

setsockopt needs a const char * :-/

**Comment by Lichtso** [comment]
Then try both `static_cast<const void*>(&flag2)` and `static_cast<const char*>(&flag2)`
The advantage of void* would be its cross platform compatibility.

**Comment by DJuego** [comment]
I try:

```cpp
unsigned int flag2 = 0;
 if(setsockopt(handle, IPPROTO_IPV6, IPV6_V6ONLY, static_cast<const void*>(&flag2), sizeof(flag2)) == -1) 
```
I get:

```
P:\Compilados\x32-x64\TRABAJO_MSVC2015_x64\netlink\src\Socket.cpp(229): error C2664: 'int setsockopt(SOCKET,int,int,const char *,int)': cannot convert argument 4 from 'const void *' to 'const char *'
P:\Compilados\x32-x64\TRABAJO_MSVC2015_x64\netlink\src\Socket.cpp(229): note: Conversion from 'void*' to pointer to non-'void' requires an explicit cast
```

I try:

```cpp
unsigned int flag2 = 0;
 if(setsockopt(handle, IPPROTO_IPV6, IPV6_V6ONLY, static_cast<const char*>(&flag2), sizeof(flag2)) == -1) 
```
I get:

```
P:\Compilados\x32-x64\TRABAJO_MSVC2015_x64\netlink\src\Socket.cpp(229): error C2440: 'static_cast': cannot convert from 'unsigned int *' to 'const char *'
P:\Compilados\x32-x64\TRABAJO_MSVC2015_x64\netlink\src\Socket.cpp(229): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
```

**Comment by Lichtso** [comment]
Oh, yes I am stupid, it hast to be `reinterpret_cast` not `static_cast`, sorry.
`reinterpret_cast<const char*>(&flag2)`

**Comment by DJuego** [comment]
Stupid??? You are a MACHINE. It works!! 💯 

I tested the tcp.cpp sample with `initAsTcpServer("::0", 3823);` and `initAsTcpServer("*", port);` and it works!

Thank you very much for your very swift support!

DJuego

**Comment by Lichtso** [comment]
I just committed all of these into 3b5a11e

Thank you for your support, too!
