### ISSUE TITLE
error LNK2019: 无法解析的外部符号 "void __cdecl netLink::init(void)" 

### ISSUE THREAD

**Issue by YiShuiHanFeng** [Lichtso/netLink#23]
Hi,I used vs2015 and the tcp example, but there is a problem
error LNK2019: 无法解析的外部符号 "void __cdecl netLink::init(void)" 
what should i do?

**Comment by Lichtso** [comment]
Seems like a missing linkage of the compiled library.
Could you solve it on your own?
