### ISSUE TITLE
Runs only on Unix

### ISSUE THREAD

**Issue by d223chen** [Lichtso/netLink#26]
You should probably state that this library only compiles on Unix systems, as the following block in Core.h:

#include <arpa/inet.h>
#include <sys/fcntl.h>
#include <netdb.h>
#include <sys/ioctl.h>
#include <unistd.h>

are not available on Windows. I get errors for each line saying "Cannot open source file ____".

**Comment by d223chen** [comment]
Hi Lichtso,

Thanks for your reply. Yeah, I noticed the macro switch after posting this.

Specifics: Windows 10, Visual Studio 2017 version 15.7.2 (updated yesterday) building to x86. Using the Clang/LLVM compiler for x64 machine, LLVM version 6.0.0.

**Comment by Lichtso** [comment]
You could also try to add the macro as command line option like this:
`clang++ ... -DWINVER=0x0A00 ...`

**Comment by d223chen** [comment]
Hi Lichtso, I think you should consider changing the switch from 

         #ifdef WINVER

to

         #ifdef _MSC_VER

as according to [this Microsoft document](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros), WINVER is not guaranteed to be defined by MSVC. _MSC_VER however, is.

That might explain the problem I had in this thread where my compiler didn't hit the switch even though it was MSVC.

**Comment by Lichtso** [comment]
Can you try replacing all 6 occurrences (across the source code) of WINVER by _MSC_VER ?
