### ISSUE TITLE
Sending Message packet

### ISSUE THREAD

**Issue by BruceWashington13** [Lichtso/netLink#29]
Hi, @Lichtso 

 i found difficulties sending data over another ip using TCP server. Likely in your code just receiving method define. What about sending data method to source. if you can guide me.

your code is 

 socket->hostRemote = (socket->getIPVersion() == netLink::Socket::IPv4) ? "224.0.0.100" : "FF02:0001::";
    socket->portRemote = socket->portLocal;

    // Join the multicast group to receive messages from the given address
    socket->setMulticastGroup(socket->hostRemote, true);

    // Prepare a MsgPack encoded message
    netLink::MsgPackSocket& msgPackSocket = *static_cast<netLink::MsgPackSocket*>(socket.get());
    msgPackSocket << MsgPack::Factory("Hello World!");
    //msgPackSocket << MsgPack__Factory(ArrayHeader(2));
    msgPackSocket << MsgPack__Factory(ArrayHeader(3));
    msgPackSocket << MsgPack__Factory(MapHeader(2));
    msgPackSocket << MsgPack::Factory("Boolean");
    msgPackSocket << MsgPack::Factory(true);
    msgPackSocket << MsgPack::Factory("Number");
    msgPackSocket << MsgPack::Factory(2487.348);
    msgPackSocket << MsgPack__Factory(ArrayHeader(0));
    msgPackSocket << MsgPack::Factory();
this source code for UDP which i show in your Example folder. i get that idea about socket manager but now i am trying to send data to another pc using tcp server and i am new in this socket field. If you can help me.

instead of multicast group just sending to only one destination using TCP Server id. if you know how...

thank you..  
Bruce Washington

**Comment by Lichtso** [comment]
In TCP a connection has to be established from a client to a server, before any data can be transferred.

0. Setup event handlers like `socketManager.onConnectRequest, socketManager.onStatusChange, socketManager.onReceiveMsgPack`
1. Open a TCP server on one PC: `socket->initAsTcpServer("*", samePort)` "*" means it accepts connections from all source IP-Addresses.
2. Open a TCP client on another PC:  `socket->initAsTcpClient(ServersIPAddress, samePort)`
3. Poll using `socketManager.listen();` which will call the previously installed event handlers

Note: Only the client needs to know the IP-Address of the server. And both must use the same port.

[Further Examples](https://github.com/Lichtso/netLink/blob/master/src/examples/tcp.cpp)

**Comment by BruceWashington13** [comment]
@Lichtso , I know this one. Now I have to send data. Not receive . Because I wrote down for receiving data using your example code. Same data which I received now send again same source. This is my question ...

Thank you

**Comment by Lichtso** [comment]
Ok, so you want an echo, which sends back what it has received.
You you use MsgPack or raw data for communication?

E.g. in the `socketManager.onReceiveMsgPack` you get a `std::shared_ptr<netLink::Socket> socket` parameter, which allows you not only to receive but also to answer (send back). Just cast it to a `MsgPackSocket` if you are using MsgPack:
`netLink::MsgPackSocket& msgPackSocket = *static_cast<netLink::MsgPackSocket*>(socket.get());`

**Comment by BruceWashington13** [comment]
@Lichtso , thanks for your help. 
i can use something like that
netLink::MsgPackSocket& msgPackSocket = *static_cast<netLink::MsgPackSocket*>(socket.get('nickname', function (err, name))) {
  console.log('Chat message by ', name);
  console.log('error ', err);
  sender = name;
});

if it is wrong correct me. i have another question can use same method to send live cctv camera streaming to another PC??

Thank you..

**Comment by Lichtso** [comment]
1. When sending raw data using `socket->send(p, sizeof(p));` you don't need `msgPackSocket`.
2. `p=NULL;` is unnecessary.
3. To stream live audio / video you should use UDP instead of TCP because you want it to be fast not accurate.

**Comment by BruceWashington13** [comment]
@Lichtso  thank you again..
if i  use msgPackSocket.. then how can you write code for this? .
second question is UDP has no error recovery if they missed some frame that will problem for software??
thank you

**Comment by Lichtso** [comment]
1. Wiki page how to use [MsgPack](https://github.com/Lichtso/netLink/wiki/MsgPack)
2. Depends on the encoding & container formats used. See ["TCP vs UDP on video stream"](https://stackoverflow.com/questions/6187456/tcp-vs-udp-on-video-stream)

**Comment by BruceWashington13** [comment]
@Lichtso , thanks a lot. it's helpful for me... i understand many things from this code and your links....

**Comment by BruceWashington13** [comment]
@Lichtso , i have one final question in my code

  netLink::MsgPackSocket& msgPackSocket2 = *static_cast<netLink::MsgPackSocket*>(socket.get());
    msgPackSocket2 << MsgPack::Factory("Hello, Multicast Group!");

    netLink::MsgPackSocket& msgPackSocket = *static_cast<netLink::MsgPackSocket*>(socket2.get());
    msgPackSocket << MsgPack::Factory("Hello, Multicast Group!");
    msgPackSocket << MsgPack__Factory(ArrayHeader(3));
    msgPackSocket << MsgPack__Factory(MapHeader(2));
    msgPackSocket << MsgPack::Factory("Boolean");
    msgPackSocket << MsgPack::Factory(true);
    msgPackSocket << MsgPack::Factory("Number");
    msgPackSocket << MsgPack::Factory(2487.348);
    msgPackSocket << MsgPack__Factory(ArrayHeader(0));
msgPackSocket << MsgPack::Factory();

this is sending method or receiving method because past two days i am stuck in this netLink. I am confused about this stuff.  i don't understand this one clearly.... please help me @Lichtso 
if this is sending.. please explain how it works. i am running out patience .

thank you....

**Comment by BruceWashington13** [comment]
@Lichtso that makes sense. How can i miss those basic things. Thanks again great work. Thanks you
