### ISSUE TITLE
How to reconnect?

### ISSUE THREAD

**Issue by dumbo1985** [Lichtso/netLink#32]
Thank you for sharing this code!

I wrote a tcp client.
When I closed tcp server, the client won't reconnect..

Please teach me how to reconnect the tcp server, Thank's a lot!

**Comment by dumbo1985** [comment]
@Lichtso Thank you !

**Comment by Lichtso** [comment]
If you take a look at the [TCP Example](https://github.com/Lichtso/netLink/blob/master/src/examples/tcp.cpp#L56) line 56 covers the connection loss case. Here you could trigger a retry and decrement a counter (as you probably only want 3 retries for example). The retry itself is identical to the first connection setup: `socket->initAsTcpClient(...)`
