### ISSUE TITLE
NetLink Sockets C++ Author HERE -> License Problem

### ISSUE THREAD

**Issue by PedroPareja** [Lichtso/netLink#35]
Hi,

I am Pedro Pareja. I am the author of NetLink Sockets C++ (https://sourceforge.net/projects/netlinksockets/ and now also in https://github.com/PedroPareja/netlink-sockets-cpp).

_Your library is based in my work_ and it would have been nice to include some reference about it. I have noticed in the history of the files that you did at first in the header of the files, but at some point you removed it:

```
    NetLink Sockets: Networking C++ library
    Copyright 2012 Pedro Francisco Pareja Ruiz (PedroPareja@Gmail.com)
    Modified 2013 Alexander Meißner (lichtso@gamefortec.net)

    This file is part of NetLink Sockets.

    NetLink Sockets is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    NetLink Sockets is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with NetLink Sockets. If not, see <http://www.gnu.org/licenses/>.

```
Apart from that there's a **license problem** as NetLink Sockets C++ is under the **GPL v3 License**:

_"Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights."_

That means that the derived work must preserve the GPL v3 license.

Please fix this licensing problem.

Congrats on your work with the library, keep it up.

**Comment by PedroPareja** [comment]
Sorry, but this is not how the GPL license works. 

Even if all the code is "new", this is a derivative work from the original so **all this "new" code must be under the GPL license** as well, as the original code.

Hiding the original history/commits of the project does not solve anything nor is a solution.

**Comment by Lichtso** [comment]
> Even if all the code is "new", this is a derivative work from the original so all this "new" code must be under the GPL license as well, as the original code.

What if somebody other than me copied all the new code (without the commit history) in a different repository?
How would this still be derivative work if its entire content is different? And not just trivially different like renaming or refactoring things, it even has a different feature set, problems it addresses, use cases etc. It shares similarity only by the project name and general topic. This is basically the [Ship of Theseus](https://en.wikipedia.org/wiki/Ship_of_Theseus) paradox.

> Hiding the original history/commits of the project does not solve anything nor is a solution.

I did not come up with that, it is literally from the "make the changes identified in the following notice:" section of the DMCA Takedown Notice I received through GitHub.

Anyway, if a change back to GPL licensing is all you want then I am fine with that as well.

**Comment by PedroPareja** [comment]
All I want is the GPL license to be honored.

**Comment by Lichtso** [comment]
Ok, done. Please check if I missed anything.
Hope the [GitHub outage](https://downdetector.com/status/github/) of today is resolved by now.

**Comment by PedroPareja** [comment]
All cool, the issue is solved
