### ISSUE TITLE
Understanding the deserialization...

### ISSUE THREAD

**Issue by DJuego** [Lichtso/netLink#7]
Hi! Your netlink library seems interesting. :-) Unfortunately i am a newbie in serialization. I have been studying  your examples and I have problems understanding how to deserialize when a socket receives data. And yes . I have read your MsgPack Tutorial. Please. Could you extend the current examples? Could you add new compilable samples with the full serialization/deserialization process? Thanks! :-)

**Comment by Lichtso** [comment]
Well the entire library is quite modular and split into 3 big parts:
1. MsgPack : Byte stream serialization and deserialization
2. Socket : Transfering data over network (connection based and message based)
3. SocketManager : Handling events and managing multiple sockets at once
of which the first 2 could stand alone.

The current MsgPack tutorial actually only describes, how serialization and deserialization works, without any kind of networking. (You could also store and load MsgPack to/from disk for example).
So when you want to transfer a message, you have to serialize it using MsgPack, then send it using a Socket and listen on the other side using a Socket and a SocketManager. The SocketManager will then trigger a callback when the message arrives.

Here are 2 examples (UDP / TCP) which do both each (serialization sending and deserialization receiving):
https://github.com/Lichtso/netLink/tree/master/src/examples

Is this what you wanted to know or is there something else?

**Comment by DJuego** [comment]
Thank you for your very swift answer! I will try to be very concrete (I suspect than my question is very basic and silly probably) . 

In very simple terms, my doubt is: how can i get a std:string var with the message "Hello World!" on the other side .  How i can 'parser' "*element"? in onReceiveMsgPack callback?  (and for extension with any other var/vector). Hopefully, with the code chunk i could begin to understand... :-/

With

  //Define a callback, fired when a socket receives data
    socketManager.onReceiveMsgPack = [](netLink::SocketManager* manager, std::shared_ptr<netLink::Socket> socket, std::unique_ptr<MsgPack::Element> element) {
        //hostRemote and portRemote are now set to the origin of the last received message
        std::cout << "Received data from " << socket->hostRemote << ":" << socket->portRemote << ": " 
<< *element << "\n";
    };

I get:

Accepted connection from 127.0.0.1:20601
Received data from 127.0.0.1:20601: {"type": "post", "message": "Hello World!"}

But i want:

Accepted connection from 127.0.0.1:20601
Received data from 127.0.0.1:20601: {"type": "post", "message": "Hello World!"}
The message is ""Hello World!"

Thanks in advance. :-}

**Comment by Lichtso** [comment]
Ok, so what onReceiveMsgPack gives you is a std::unique_ptr<MsgPack::Element> element.
This std::unique_ptr contains at least one MsgPack::Element or a entire hierarchy of MsgPack::Elements.
You could start by doing something like:

    auto elementMap = dynamic_cast<MsgPack::Map*>(element.get());
    if(elementMap) { // The received element is a map
        auto container = elementMap->getContainer();
        // Iterate them
        for(auto& elementInContainer : *container) {
            auto str = dynamic_cast<MsgPack::String*>(elementInContainer.get());
            if(str) { // elementInContainer is a string
                std::cout << *elementInContainer << std::endl;
            }
        }
        // Or just access them directly
        if(container->size() >= 4) {
            auto firstKey = static_cast<MsgPack::String*>((*container)[0].get()); // Key are allways strings and at even indecies
            auto firstValue = (*container)[1].get(); // Values might be of any type and are allways at odd indecies
            auto secondKey = static_cast<MsgPack::String*>((*container)[2].get()); // Key are allways strings and at even indecies
            auto secondValue = (*container)[3].get(); // Values might be of any type and are allways at odd indecies
            // ... and so on
            std::cout << firstKey->stdString() << " : " << *firstValue << std::endl;
            std::cout << secondKey->stdString() << " : " << *secondValue << std::endl;
        }
    }

Well a bit strange, Maps are handled as std::vector but they would be much harder to use if they were std::map and you can get information about the order too in a std::vector.

Here is the online documentation:
http://lichtso.github.io/netLink/doc/annotated.html

**Comment by DJuego** [comment]
Yes! I see. :-) Thank you! A very fast and good support. :-} It is probably i use your library. A good discovery, i think. However, i can not assure to you yet. Tomorrow, i will know more, i hope. :-)

**Comment by Lichtso** [comment]
I added some convenience methods to access key/values directly:

    std::cout << "Access them directly:" << std::endl;
    auto firstKey = elementMap->getKey(0);
    auto firstValue = elementMap->getValue(0);
    auto secondKey = elementMap->getKey(1);
    auto secondValue = elementMap->getValue(1);

and updated the examples and documentation.
